[app]
cacheDir = "./cache/"
pubKey = ""
version = 0 # 0=debug 1=release
pid = "gin_demo"

[httpServer]
addr = ":8080"
port = 8080


[log]
dir = "./log/"
Stdout = true

[db]
dsn = "root:root@tcp(127.0.0.1:3306)/online?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2
idleTimeout = 345600
debug = true
prefix = "control_"
#    queryTimeout = 1
#    execTimeout = 1
#    tranTimeout = 1

